* sillysecrets
command name: =sesi= (i swapped the vowels because i'm evil >:3)

A group-oriented secret storage tool,
inspired by [[https://github.com/getsops/sops][sops]] and using [[https://github.com/FiloSottile/age][age]] for encryption.

** Groups
The primary structure of sillysecrets.
They are made up of the following fields, all of which are optional:
- =key=: the public key for which secrets of this groups are encrypted.
- =contains=: list of group names whose secrets should be encrypted for this group too
- =grants=: list of group names for which the secrets of this group should be encrypted too
- =secrets=: the actual set of secrets

** Usage
1. Create a =sesi.yaml= file to store your groups.
   Take a look at the [[file:example/sesi.yaml][example]] for reference.
   Do *not* fill in any secrets; they are created using the =edit= subcommand instead.
2. Run =sesi edit <group>.<secret>= for every secret you want to create.
   This command will create new, empty secrets or edit their current value.
   [[https://man.archlinux.org/man/vipe.1][vipe]] from the =moreutils= package will be used as your temporary editor.
3. If you simply want to read an existing secret, use =sesi decrypt <group>.<secret>=
4. After changing the grants & contains lists or any group's key,
   you need to run =sesi rekey= in order to propagate these changes to the secrets.
   This will attempt to de- and reencrypt every secret
   while skipping over those it can't decrypt (because of missing identity files).
